spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:oracle:thin:@//localhost:1521/xe}
    username: ${JDBC_DATABASE_USERNAME:PIPPO}
    password: ${JDBC_DATABASE_PASSWORD:PIPPO}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
